# Numpy

#### Numpy is general purpose-processing package.it provides high performance multidimensional array object,and tools for working with these arrays.it is the fundamental package for scientific computing with python

## what is an array?


#### An array is data strucure that stores values of same data type,In python,this is the main differnce between arrays and lists,while python lists can contains values corresponding to differnt data types,arrays in python can only contain values corresponding to the sam data type

In [164]:
## initially lets import numpy

import numpy as np

In [2]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)


In [3]:
type(arr)

numpy.ndarray

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.shape

(5,)

In [7]:
type(arr)

numpy.ndarray

In [32]:
## multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[7,8,9,1,9]

arr=np.array([my_lst1,my_lst2,my_lst3])



In [10]:
arr


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [7, 8, 9, 1, 9]])

In [14]:
## check the shape of array
arr.shape

(3, 5)

In [15]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 7, 8],
       [9, 1, 9]])

# Indexing

In [49]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [7, 8, 9, 1, 9]])

In [51]:
arr[:,:]                  #: means it picked up all the elements

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [7, 8, 9, 1, 9]])

In [52]:
arr[1:,3:]                # adding particular row and column number for particular indexing 

array([[5, 6],
       [1, 9]])

In [53]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [54]:
arr[1:,3:]

array([[5, 6],
       [1, 9]])

In [67]:
arr[0:2,1:4]

array([[2, 3, 4],
       [3, 4, 5]])

In [75]:
arr[1:,1:4]

array([[3, 4, 5],
       [8, 9, 1]])

In [83]:
arr[1:3,2:4]

array([[4, 5],
       [9, 1]])

In [88]:
arr=np.arange(0,10,step=2)

In [90]:
arr

array([0, 2, 4, 6, 8])

In [91]:
np.linspace(1,10,50)            # basically equaled spaced points

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [92]:
# copy() function and broadcasting
arr

array([0, 2, 4, 6, 8])

In [97]:
arr[2:]=100

In [98]:
arr

array([  0,   2, 100, 100, 100])

In [99]:
arr1=arr

In [101]:
arr1[2:]=500
print(arr1)

[  0   2 500 500 500]


In [102]:
arr

array([  0,   2, 500, 500, 500])

In [103]:
arr1=arr.copy()

In [105]:
print(arr)
arr1[2:]=1000
print(arr1)

[  0   2 500 500 500]
[   0    2 1000 1000 1000]


In [ ]:
## Some conditions very useful exploratary data analysis

In [113]:
val=2

arr[arr>2]

array([500, 500, 500])

In [118]:
# Create arrays and reshape

arr

array([  0,   2, 500, 500, 500])

In [136]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [141]:
## Random distibution

np.random.rand(3,3)

array([[0.9744983 , 0.06094802, 0.01650855],
       [0.87733301, 0.06183645, 0.01429062],
       [0.32060131, 0.84072324, 0.00736821]])

In [142]:
arr_ex=np.random.rand(4,4)

In [146]:
arr_ex

array([[0.55510022, 0.36284304, 0.92940033, 0.73015091],
       [0.03634558, 0.91970107, 0.65562388, 0.31808365],
       [0.72101853, 0.86368214, 0.14982815, 0.15748687],
       [0.38809325, 0.96841695, 0.04224156, 0.02109247]])